name: CI Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # 1. Repository 체크아웃
            - name: Checkout code
              uses: actions/checkout@v3

            # 2. Node.js 버전 설정
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            # 3. 의존성 설치
            - name: Install dependencies
              run: npm ci

            # 4. 테스트 실행
            - name: Run tests
              run: npm test
